version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - counter
  counter:
    build:
      context: .
      dockerfile: Dockerfile
    command: node controllers/counter.js
    volumes:
      - ./uploads:/app/uploads
