

version: '3'
services:
  books-app:
    build:
      context: ./express
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./uploads:/app/uploads
    depends_on:
      - counter-app
  counter-app:
    build:
      context: ./counter-app
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/uploads


